/* eslint-disable @typescript-eslint/no-explicit-any */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 gallery4.glb --transform -k -s -S 
Files: gallery4.glb [6.21MB] > /Users/stephen/Downloads/gallery4-transformed.glb [1.13MB] (82%)
Author: stoneysteiner (https://sketchfab.com/stoneysteiner)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/landscape-gallery-by-stoneysteiner-3702735762544e5796be4740cb6d5efc
Title: Landscape gallery by @stoneysteiner
*/

const imagesMeta = [
  {
    id: 0,
    url: "https://twitter.com/monad_xyz/status/1758578443011186822",
    image: "https://pbs.twimg.com/media/GGe5xWDWYAEACdT?format=jpg&name=large",
  },

  {
    id: 1,
    url: "https://twitter.com/monad_xyz/status/1758578443011186822",
    image: "https://pbs.twimg.com/media/GGe5xWKWQAEv4vw?format=jpg&name=large",
  },

  {
    id: 2,
    url: "https://twitter.com/monad_xyz/status/1761086942626886061",
    image:
      "https://pbs.twimg.com/media/GHCjJxqaQAAf6Za?format=jpg&name=4096x4096",
  },

  {
    id: 3,
    url: "https://twitter.com/monad_xyz/status/1758578443011186822",
    image: "https://pbs.twimg.com/media/GGe5xWCWwAAN55c?format=jpg&name=large",
  },

  {
    id: 4,
    url: "https://twitter.com/monad_xyz/status/1763629978577760563",
    image: "https://pbs.twimg.com/media/GHmsAdga0AAZEXZ?format=jpg&name=large",
  },

  {
    id: 5,
    url: "https://twitter.com/monad_xyz/status/1763629978577760563",
    image:
      "https://pbs.twimg.com/media/GHmr-kwbEAAwqLF?format=jpg&name=4096x4096",
  },

  {
    id: 6,
    url: "https://twitter.com/monad_xyz/status/1753488817468969307",
    image: "https://pbs.twimg.com/media/GFWksMnbkAMr5yK?format=jpg&name=large",
  },

  {
    id: 7,
    url: "https://twitter.com/monad_xyz/status/1750960066168299898",
    image: "https://pbs.twimg.com/media/GEyo4VibIAEh2du?format=jpg&name=large",
  },

  {
    id: 8,
    url: "https://twitter.com/monad_xyz/status/1748403213274120220",
    image: "https://pbs.twimg.com/media/GEOTMfwacAAlaTC?format=jpg&name=large",
  },

  {
    id: 9,
    url: "https://twitter.com/monad_xyz/status/1748403213274120220",
    image: "https://pbs.twimg.com/media/GEOTOjjbAAAEPbH?format=jpg&name=large",
  },

  {
    id: 10,
    url: "https://twitter.com/monad_xyz/status/1748403213274120220",
    image:
      "https://pbs.twimg.com/media/GEOTQUVbAAEcdzk?format=jpg&name=4096x4096",
  },

  {
    id: 11,
    url: "https://twitter.com/monad_xyz/status/1745866042579042459",
    image: "https://pbs.twimg.com/media/GDqP4sKWoAEYDYF?format=jpg&name=large",
  },
];

import { useGLTF, useTexture } from "@react-three/drei";

export default function Model(props: any) {
  const textures = [
    useTexture(imagesMeta[0].image),
    useTexture(imagesMeta[1].image),
    useTexture(imagesMeta[2].image),
    useTexture(imagesMeta[3].image),
    useTexture(imagesMeta[4].image),
    useTexture(imagesMeta[5].image),
    useTexture(imagesMeta[6].image),
    useTexture(imagesMeta[7].image),
    useTexture(imagesMeta[8].image),
    useTexture(imagesMeta[9].image),
    useTexture(imagesMeta[10].image),
    useTexture(imagesMeta[11].image),
  ];

  const { nodes, materials } = useGLTF("/gallery4-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Cube_0"
        castShadow
        receiveShadow
        geometry={nodes.Cube_0.geometry}
        material={materials.Walls}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube003_0"
        castShadow
        receiveShadow
        geometry={nodes.Cube003_0.geometry}
        material={materials.Frame}
        position={[0, 0.344, 0]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        name="Cube003_1"
        castShadow
        receiveShadow
        geometry={nodes.Cube003_1.geometry}
        position={[0, 0.344, 0]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      >
        <meshBasicMaterial map={textures[0]} />
      </mesh>
      <mesh
        name="Cube003_2"
        castShadow
        receiveShadow
        geometry={nodes.Cube003_2.geometry}
        position={[0, 0.344, 0]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      >
        <meshBasicMaterial map={textures[1]} />
      </mesh>

      <mesh
        name="Cube003_3"
        castShadow
        receiveShadow
        geometry={nodes.Cube003_3.geometry}
        // material={materials.Picture03}
        position={[0, 0.344, 0]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      >
        <meshBasicMaterial map={textures[2]} />
      </mesh>
      <mesh
        name="Cube003_4"
        castShadow
        receiveShadow
        geometry={nodes.Cube003_4.geometry}
        position={[0, 0.344, 0]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      >
        <meshBasicMaterial map={textures[3]} />
      </mesh>
      <mesh
        name="Cube003_5"
        castShadow
        receiveShadow
        geometry={nodes.Cube003_5.geometry}
        position={[0, 0.344, 0]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      >
        <meshBasicMaterial map={textures[4]} />
      </mesh>
      <mesh
        name="Cube003_6"
        castShadow
        receiveShadow
        geometry={nodes.Cube003_6.geometry}
        // material={materials.Picture09}
        position={[0, 0.344, 0]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      >
        <meshBasicMaterial map={textures[5]} />
      </mesh>

      <mesh
        name="Cube003_7"
        castShadow
        receiveShadow
        geometry={nodes.Cube003_7.geometry}
        // material={materials.Picture04}
        position={[0, 0.344, 0]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      >
        <meshBasicMaterial map={textures[6]} />
      </mesh>

      <mesh
        name="Cube003_8"
        castShadow
        receiveShadow
        geometry={nodes.Cube003_8.geometry}
        // material={materials.Picture05}
        position={[0, 0.344, 0]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      >
        <meshBasicMaterial map={textures[7]} />
      </mesh>

      <mesh
        name="Cube003_9"
        castShadow
        receiveShadow
        geometry={nodes.Cube003_9.geometry}
        // material={materials.Picture06}
        position={[0, 0.344, 0]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      >
        <meshBasicMaterial map={textures[8]} />
      </mesh>

      <mesh
        name="Cube003_10"
        castShadow
        receiveShadow
        geometry={nodes.Cube003_10.geometry}
        // material={materials.Picture10}
        position={[0, 0.344, 0]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      >
        <meshBasicMaterial map={textures[9]} />
      </mesh>

      <mesh
        name="Cube003_11"
        castShadow
        receiveShadow
        geometry={nodes.Cube003_11.geometry}
        // material={materials.Picture11}
        position={[0, 0.344, 0]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      >
        <meshBasicMaterial map={textures[10]} />
      </mesh>

      <mesh
        name="Cube003_12"
        castShadow
        receiveShadow
        geometry={nodes.Cube003_12.geometry}
        // material={materials.Picture12}
        position={[0, 0.344, 0]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      >
        <meshBasicMaterial map={textures[11]} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/gallery4-transformed.glb");
